# Generated by Django 4.2.1 on 2023-05-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
