# Generated by Django 4.2.1 on 2023-05-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeManager', '0002_empreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreview',
            name='pics',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='empreview',
            name='rating',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
