# Generated by Django 4.2.1 on 2023-05-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeManager', '0003_empreview_pics_empreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreview',
            name='department',
            field=models.CharField(default='Company Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='empreview',
            name='name',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
        migrations.AlterField(
            model_name='empreview',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
